# Generated by Django 4.1.7 on 2023-06-25 17:48

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Immo",
            fields=[
                ("idimmo", models.AutoField(primary_key=True, serialize=False)),
                ("serial_number", models.TextField()),
                ("description", models.TextField()),
                ("date_of_commissioning", models.DateField()),
                ("cost_account", models.FloatField()),
                ("depreciation_period", models.IntegerField()),
                ("amount_per_hour", models.FloatField(null=True)),
                ("usage", models.FloatField()),
                ("image", models.ImageField(null=True, upload_to="immo_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unite_mesure", models.CharField(max_length=255)),
                ("item_type", models.CharField(max_length=255)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                ("land_id", models.AutoField(primary_key=True, serialize=False)),
                ("surface", models.JSONField()),
                ("lat", models.FloatField()),
                ("lang", models.FloatField()),
                ("sensor_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lineno", models.IntegerField()),
                ("lot_number", models.IntegerField()),
                ("item_id", models.IntegerField()),
                ("estimated_quantity", models.IntegerField()),
                ("real_quantity", models.IntegerField()),
                ("estimated_amount", models.FloatField()),
                ("real_amount", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductionHeader",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("lot_number", models.IntegerField()),
                ("produced_item", models.CharField(max_length=255)),
                ("estimated_amount", models.FloatField()),
                ("start_date", models.DateField()),
                ("estimated_end_date", models.DateField()),
                ("surface", models.FloatField()),
                ("current_status", models.CharField(max_length=255)),
                ("final_status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderHeader",
            fields=[
                ("order_no", models.IntegerField(primary_key=True, serialize=False)),
                ("order_type", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("supplier_id", models.IntegerField()),
                ("requested_date", models.DateField(null=True)),
                ("order_date", models.DateField()),
                ("scheduled_pick_date", models.DateField(null=True)),
                ("actual_ship_date", models.DateField(null=True)),
                ("cancel_date", models.DateField(null=True)),
                ("date_received", models.DateField(null=True)),
                ("price_effective_date", models.DateField(null=True)),
                ("promised_shipment_date", models.DateField(null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("order_gross_amount", models.FloatField()),
                ("currency_mode", models.CharField(max_length=255)),
                ("foreign_open_amount", models.FloatField(null=True)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StockTransactions",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_id", models.IntegerField()),
                ("transaction_type", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("cost", models.FloatField()),
                ("transaction", models.DateTimeField()),
                ("user_id", models.IntegerField()),
                ("rmk", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierMaster",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=255)),
                ("supplier_address", models.CharField(max_length=255)),
                ("supplier_contact", models.CharField(max_length=255)),
                ("supplier_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_type", models.CharField(max_length=255)),
                ("company", models.IntegerField()),
                ("line_no", models.IntegerField()),
                ("item_id", models.IntegerField()),
                ("supplier_id", models.IntegerField()),
                ("requested_date", models.DateField()),
                ("date_received", models.DateField(null=True)),
                ("order_date", models.DateField()),
                ("scheduled_pick_date", models.DateField()),
                ("actual_ship_date", models.DateField()),
                ("cancel_date", models.DateField(null=True)),
                ("promised_shipment_date", models.DateField()),
                ("remark", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("unit", models.CharField(max_length=255)),
                ("unit_cost", models.FloatField()),
                ("order_gross_amount", models.FloatField()),
                ("currency_mode", models.CharField(max_length=255)),
                ("foreign_amount", models.FloatField()),
                ("status", models.CharField(max_length=255)),
                (
                    "order_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.purchaseorderheader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "lineno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productiondetail",
                    ),
                ),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionheader",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productiondetail",
            name="transaction_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.productionheader"
            ),
        ),
        migrations.CreateModel(
            name="ItemPDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produced_item", models.CharField(max_length=255)),
                ("composed_item", models.CharField(max_length=255)),
                ("unite_mesure", models.CharField(max_length=255)),
                (
                    "lineno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productiondetail",
                    ),
                ),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionheader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unit_cost", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("warehouse", models.CharField(max_length=255)),
                ("item_type", models.CharField(max_length=255)),
                ("item_measure", models.CharField(max_length=255)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndirectProductionExp",
            fields=[
                ("lineno", models.IntegerField(primary_key=True, serialize=False)),
                ("lot_number", models.IntegerField()),
                ("idimmo", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("unite_de_mesure", models.CharField(max_length=255)),
                ("unit_cost", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("amount", models.FloatField()),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionheader",
                    ),
                ),
            ],
        ),
    ]
