# Generated by Django 4.1.7 on 2023-03-26 21:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('ItemID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ItemDescription', models.CharField(max_length=255)),
                ('UniteMesure', models.FloatField()),
                ('ItemType', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderHeader',
            fields=[
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderType', models.CharField(max_length=255)),
                ('Company', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('RequestedDate', models.DateField()),
                ('OrderDate', models.DateField()),
                ('ScheduledPickDate', models.DateField()),
                ('ActualShipDate', models.DateField()),
                ('CancelDate', models.DateField()),
                ('DateReceived', models.DateField()),
                ('PriceEffectiveDate', models.DateField()),
                ('PromisedShipmentDate', models.DateField()),
                ('Remark', models.TextField()),
                ('OrderGrossAmount', models.FloatField()),
                ('CurrencyMode', models.CharField(max_length=255)),
                ('ForeignOpenAmount', models.FloatField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemID', models.IntegerField()),
                ('TransactionType', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Cost', models.FloatField()),
                ('Transaction', models.DateTimeField()),
                ('UserID', models.IntegerField()),
                ('Rmk', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=255)),
                ('supplier_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderType', models.CharField(max_length=255)),
                ('Company', models.IntegerField()),
                ('LineNo', models.IntegerField()),
                ('ItemID', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('RequestedDate', models.DateField()),
                ('DateReceived', models.DateField()),
                ('OrderDate', models.DateField()),
                ('ScheduledPickDate', models.DateField()),
                ('ActualShipDate', models.DateField()),
                ('CancelDate', models.DateField()),
                ('PromisedShipmentDate', models.DateField()),
                ('Remark', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('Unit', models.CharField(max_length=255)),
                ('UnitCost', models.FloatField()),
                ('OrderGrossAmount', models.FloatField()),
                ('CurrencyMode', models.CharField(max_length=255)),
                ('ForeignAmount', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('OrderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchaseorderheader')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('Quantity', models.IntegerField()),
                ('UnitCost', models.FloatField()),
                ('TotalCost', models.FloatField()),
                ('Warehouse', models.CharField(max_length=255)),
                ('ItemType', models.CharField(max_length=255)),
                ('ItemMeasure', models.CharField(max_length=255)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
