# Generated by Django 4.1.7 on 2023-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("land_id", models.DecimalField(decimal_places=2, max_digits=10)),
                ("surface", models.JSONField()),
                ("lat", models.FloatField()),
                ("lang", models.FloatField()),
            ],
        ),
    ]
