# Generated by Django 4.1.7 on 2023-05-25 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indirectproductionexp",
            old_name="lot_id",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="itempdetail",
            old_name="lot_id",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="productiondetail",
            old_name="lot_id",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="productionheader",
            old_name="lot_id",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="productionstatus",
            old_name="lot_id",
            new_name="transaction_id",
        ),
    ]
