# Generated by Django 4.1.7 on 2023-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="description",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
