# Generated by Django 4.1.7 on 2023-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_lot_id_indirectproductionexp_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="sensor_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
