# Generated by Django 4.1.7 on 2023-06-26 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_inventory_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="actual_ship_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="cancel_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="company",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="date_received",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="order_type",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="promised_shipment_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="remark",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="requested_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="scheduled_pick_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorderdetail",
            name="supplier_id",
        ),
    ]
