# Generated by Django 4.1.7 on 2023-05-12 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
