# Generated by Django 4.1.7 on 2023-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_land"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="land",
            name="id",
        ),
        migrations.AlterField(
            model_name="land",
            name="land_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
