# Generated by Django 4.1.7 on 2023-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_land_sensor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="cancel_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="date_received",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderdetail",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="cancel_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="date_received",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="foreign_open_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransactions",
            name="rmk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
