# Generated by Django 4.1.7 on 2023-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_item_item_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="scheduled_pick_date",
            field=models.DateField(null=True),
        ),
    ]
