# Generated by Django 4.1.7 on 2023-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_purchaseorderheader_scheduled_pick_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="actual_ship_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="price_effective_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="promised_shipment_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderheader",
            name="requested_date",
            field=models.DateField(null=True),
        ),
    ]
