# Generated by Django 4.1.7 on 2023-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_purchaseorderheader_actual_ship_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="immo",
            name="img",
        ),
        migrations.AddField(
            model_name="immo",
            name="image",
            field=models.ImageField(null=True, upload_to="immo_images/"),
        ),
        migrations.AlterField(
            model_name="immo",
            name="amount_per_hour",
            field=models.FloatField(null=True),
        ),
    ]
